import { simpleGit, type SimpleGit } from 'simple-git';
import { createLogger } from '../../utils/logger.js';

const logger = createLogger('fenice', process.env['LOG_LEVEL'] ?? 'info');

export interface GitCommitResult {
  branch: string;
  commitHash: string;
}

function slugify(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
    .slice(0, 40);
}

export async function createBranchAndCommit(
  projectRoot: string,
  jobId: string,
  prompt: string,
  filePaths: string[]
): Promise<GitCommitResult> {
  const git: SimpleGit = simpleGit(projectRoot);

  const slug = slugify(prompt);
  const branch = `builder/${jobId}-${slug}`;

  // Create and checkout new branch from current HEAD
  await git.checkoutLocalBranch(branch);
  logger.info({ branch }, 'Created builder branch');

  // Stage all generated/modified files
  await git.add(filePaths);

  // Build conventional commit message
  const shortPrompt = prompt.length > 60 ? prompt.slice(0, 60) + '...' : prompt;
  const commitMessage = [
    `feat(builder): ${shortPrompt}`,
    '',
    `Generated by AI Builder (job: ${jobId})`,
    '',
    'Files:',
    ...filePaths.map((f) => `  - ${f}`),
    '',
    'Co-Authored-By: Claude Opus 4.6 <noreply@anthropic.com>',
  ].join('\n');

  const commitResult = await git.commit(commitMessage);
  const commitHash = commitResult.commit || 'unknown';
  logger.info({ branch, commitHash }, 'Committed generated files');

  return { branch, commitHash };
}

export async function pushBranch(projectRoot: string, branch: string): Promise<void> {
  const git: SimpleGit = simpleGit(projectRoot);
  await git.push('origin', branch, ['--set-upstream']);
  logger.info({ branch }, 'Pushed branch to remote');
}

export async function cleanupBranch(projectRoot: string, branch: string): Promise<void> {
  const git: SimpleGit = simpleGit(projectRoot);

  // Switch back to main before deleting
  const currentBranch = (await git.branch()).current;
  if (currentBranch === branch) {
    await git.checkout('main');
  }

  try {
    await git.deleteLocalBranch(branch, true);
    logger.info({ branch }, 'Cleaned up builder branch');
  } catch {
    logger.warn({ branch }, 'Failed to clean up branch');
  }
}
