import { Octokit } from '@octokit/rest';
import type { BuilderGeneratedFile } from '../../schemas/builder.schema.js';
import { createLogger } from '../../utils/logger.js';

const logger = createLogger('fenice', process.env['LOG_LEVEL'] ?? 'info');

export interface PrResult {
  prUrl: string;
  prNumber: number;
}

export async function createPullRequest(
  branch: string,
  prompt: string,
  files: BuilderGeneratedFile[],
  jobId: string,
  validationPassed: boolean,
  githubToken: string,
  owner: string,
  repo: string
): Promise<PrResult> {
  const octokit = new Octokit({ auth: githubToken });

  const title = buildPrTitle(prompt);
  const body = buildPrBody(prompt, files, jobId, validationPassed);

  const { data } = await octokit.pulls.create({
    owner,
    repo,
    title,
    body,
    head: branch,
    base: 'main',
  });

  logger.info({ prNumber: data.number, prUrl: data.html_url }, 'Pull request created');

  return {
    prUrl: data.html_url,
    prNumber: data.number,
  };
}

function buildPrTitle(prompt: string): string {
  const shortPrompt = prompt.length > 55 ? prompt.slice(0, 55) + '...' : prompt;
  return `feat(builder): ${shortPrompt}`;
}

function buildPrBody(
  prompt: string,
  files: BuilderGeneratedFile[],
  jobId: string,
  validationPassed: boolean
): string {
  const createdFiles = files.filter((f) => f.action === 'created');
  const modifiedFiles = files.filter((f) => f.action === 'modified');

  const sections: string[] = [
    '## Summary',
    '',
    `> ${prompt}`,
    '',
    `Generated by AI Builder (job: \`${jobId}\`)`,
    '',
  ];

  if (createdFiles.length > 0) {
    sections.push('### New Files');
    for (const f of createdFiles) {
      sections.push(`- \`${f.path}\``);
    }
    sections.push('');
  }

  if (modifiedFiles.length > 0) {
    sections.push('### Modified Files');
    for (const f of modifiedFiles) {
      sections.push(`- \`${f.path}\``);
    }
    sections.push('');
  }

  sections.push('## Validation');
  sections.push('');
  sections.push(`- [${validationPassed ? 'x' : ' '}] TypeScript typecheck`);
  sections.push(`- [${validationPassed ? 'x' : ' '}] ESLint`);
  sections.push(`- [${validationPassed ? 'x' : ' '}] Tests`);
  sections.push('');

  sections.push('## Risk Checklist');
  sections.push('');
  sections.push('- [ ] Review generated code for correctness');
  sections.push('- [ ] Verify no hardcoded secrets or credentials');
  sections.push('- [ ] Check schema validation rules match requirements');
  sections.push('- [ ] Confirm route auth/RBAC is appropriate');
  sections.push('- [ ] Run full test suite after merge');
  sections.push('');

  sections.push('---');
  sections.push('*Generated with [FENICE AI Builder](https://github.com/formray/fenice)*');

  return sections.join('\n');
}
